<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2018.0.0.379
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Отправка Форма Zayavka',
	'heading' => 'Отправка новой формы',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Отмечено',
		'checkbox_unchecked' => 'Флажок не установлен',
		'submitted_from' => 'Формы, отправленные с веб-сайта: %s',
		'submitted_by' => 'IP-адрес посетителя: %s',
		'too_many_submissions' => 'Недопустимо высокое количество отправок с этого IP-адреса за последнее время',
		'failed_to_send_email' => 'Не удалось отправить сообщение эл. почты',
		'invalid_reCAPTCHA_private_key' => 'Недействительный закрытый ключ reCAPTCHA.',
		'invalid_reCAPTCHA2_private_key' => 'Недействительный закрытый ключ reCAPTCHA 2.0.',
		'invalid_reCAPTCHA2_server_response' => 'Недействительный ответ сервера reCAPTCHA 2.0.',
		'invalid_field_type' => 'Неизвестный тип поля \'%s\'.',
		'invalid_form_config' => 'Недопустимая конфигурация поля \"%s\".',
		'unknown_method' => 'Неизвестный метод запроса сервера'
	),
	'email' => array(
		'from' => 'zakaz@cigam.ru',
		'to' => 'zakaz@cigam.ru'
	),
	'fields' => array(
		'custom_U40326' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Имя',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U40332' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Сотовый телефон',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Сотовый телефон\' не может быть пустым.'
			)
		),
		'custom_U40533' => array(
			'order' => 6,
			'type' => 'string',
			'label' => 'Пользовательский текст',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Пользовательский текст\' не может быть пустым.'
			)
		),
		'custom_U40549' => array(
			'order' => 7,
			'type' => 'string',
			'label' => 'Пользовательский текст',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Пользовательский текст\' не может быть пустым.'
			)
		),
		'custom_U40565' => array(
			'order' => 8,
			'type' => 'string',
			'label' => 'Пользовательский текст',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Пользовательский текст\' не может быть пустым.'
			)
		),
		'custom_U41452' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'Сообщение',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U40581' => array(
			'order' => 4,
			'type' => 'radiogroup',
			'label' => 'Тип мероприятия',
			'required' => true,
			'optionItems' => array(
				'Свадьба',
				'Корпоратив',
				'Юбилей',
				'Презентация'
			),
			'errors' => array(
				'required' => 'Поле \'Тип мероприятия\' не может быть пустым.',
				'format' => 'Недопустимое значение поля \"Тип мероприятия\".'
			)
		),
		'custom_U40957' => array(
			'order' => 2,
			'type' => 'radiogroup',
			'label' => 'Необходимый тип выступления',
			'required' => true,
			'optionItems' => array(
				'Сценическое мини (15-20 мин = 8000 руб)',
				'Сценическое стандарт (25-30 мин = 10000 руб)',
				'Интерактив (1 час = 8000 руб)',
				'Иллюзион (15 мин = 15000 руб)',
				'Смешанная',
				'Заказчик не определился'
			),
			'errors' => array(
				'required' => 'Поле \'Необходимый тип выступления\' не может быть пустым.',
				'format' => 'Недопустимое значение поля \"Необходимый тип выступления\".'
			)
		)
	)
);

process_form($form);
?>
