<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2018.0.0.379
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Отправка Заявка с сайта Cigam.ru',
	'heading' => 'Отправка новой формы',
	'success_redirect' => 'spasibo.html',
	'resources' => array(
		'checkbox_checked' => 'Отмечено',
		'checkbox_unchecked' => 'Флажок не установлен',
		'submitted_from' => 'Формы, отправленные с веб-сайта: %s',
		'submitted_by' => 'IP-адрес посетителя: %s',
		'too_many_submissions' => 'Недопустимо высокое количество отправок с этого IP-адреса за последнее время',
		'failed_to_send_email' => 'Не удалось отправить сообщение эл. почты',
		'invalid_reCAPTCHA_private_key' => 'Недействительный закрытый ключ reCAPTCHA.',
		'invalid_reCAPTCHA2_private_key' => 'Недействительный закрытый ключ reCAPTCHA 2.0.',
		'invalid_reCAPTCHA2_server_response' => 'Недействительный ответ сервера reCAPTCHA 2.0.',
		'invalid_field_type' => 'Неизвестный тип поля \'%s\'.',
		'invalid_form_config' => 'Недопустимая конфигурация поля \"%s\".',
		'unknown_method' => 'Неизвестный метод запроса сервера'
	),
	'email' => array(
		'from' => 'magic@cigam.ru',
		'to' => 'magic@cigam.ru'
	),
	'fields' => array(
		'custom_U39401' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Имя',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U39407' => array(
			'order' => 2,
			'type' => 'string',
			'label' => 'Сотовый телефон',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Сотовый телефон\' не может быть пустым.'
			)
		),
		'custom_U39411' => array(
			'order' => 3,
			'type' => 'radiogroup',
			'label' => 'Выберите интересующую Вас услугу',
			'required' => true,
			'optionItems' => array(
				'Выступление для взрослых',
				'Выступление для детей (от 5 лет)',
				'Школа Волшебства (от 6 до 14 лет)',
				'Профессиональное обучение для взрослых'
			),
			'errors' => array(
				'required' => 'Поле \'Выберите интересующую Вас услугу\' не может быть пустым.',
				'format' => 'Недопустимое значение поля \"Выберите интересующую Вас услугу\".'
			)
		)
	)
);

process_form($form);
?>
